language: go
go_import_path: github.com/janekolszak/rememberme
go:
  - 1.11

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide
  - glide install

script:
  - go test $(glide nv)
